version: "3.9"
services:
  shell:
    image: willdev18/mfe_shell_activos-fijos_sw2:v1 
    ports:
      - "4200:80"
    container_name: mfe-shell

  profile:
    image: willdev18/mfe_profile_activos-fijos_sw2:cors-updated  
      - "4201:80"
    container_name: mfe-profile

  roles:
    image: willdev18/mfe_roles_activos-fijos_sw2:cors-updated
    ports:
      - "4202:80"
    container_name: mfe-roles

  users:
    image: willdev18/mfe_users_activos-fijos_sw2:cors-updated  
    ports:
      - "4203:80"
    container_name: mfe-users