server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  types {
    text/javascript js mjs;
    text/css css;
    text/html html;
    application/json json;
    image/svg+xml svg;
    image/png png;
    image/x-icon ico;
    font/woff2 woff2;
  }
  default_type application/octet-stream;

  location /api/ {
    rewrite ^/api/(.*)$ /$1 break;
    proxy_pass http://uhqu8rqq4t33xe1c0012wvrb.155.133.27.31.sslip.io;
    proxy_set_header Host uhqu8rqq4t33xe1c0012wvrb.155.133.27.31.sslip.io;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_ssl_server_name on;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}